(async function(){
    const status=document.getElementById('decorStatus'),form=document.getElementById('decorForm'),cards=document.getElementById('decorCards'),save=document.getElementById('saveDecor');
    let slides=[],version=0,selected=0,dirty=false,busy=false;
    const statusText=(text,error=false)=>{status.textContent=text;status.classList.toggle('decor-error',error)};
    if(!isLoggedIn() || !isSuperAdmin()){statusText('Connecte-toi avec ton compte super administrateur pour modifier le décor.',true);return;}
    function source(s){return s.data || new URL(s.url,API_URL).href;}
    function preview(){const s=slides[selected],img=document.getElementById('previewImage'),mobile=document.getElementById('mobilePreview').checked;document.getElementById('decorPreview').classList.toggle('is-mobile',mobile);img.hidden=!s;if(s){img.src=source(s);img.style.objectPosition=(mobile?s.mobileFocal:s.focal)+'% center';}}
    function mark(){dirty=true;statusText('Modifications non enregistrées.');}
    function button(text,callback){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=callback;return b;}
    function render(){cards.replaceChildren();slides.forEach((s,i)=>{const card=document.createElement('article');card.className='decor-card';const title=document.createElement('h3');title.textContent='Fond '+(i+1);const img=document.createElement('img');img.src=source(s);img.alt='Fond '+(i+1);img.onclick=()=>{selected=i;preview()};card.append(title,img);
        const label=document.createElement('label');label.textContent='Remplacer l’image';const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png';input.onchange=()=>readFile(input.files[0],i);label.append(input);card.append(label);
        [['focal','Cadrage ordinateur'],['mobileFocal','Cadrage mobile']].forEach(([key,text])=>{const l=document.createElement('label');l.textContent=text+' (gauche ↔ droite)';const r=document.createElement('input');r.type='range';r.min='0';r.max='100';r.value=s[key];r.oninput=()=>{s[key]=Number(r.value);selected=i;mark();preview()};l.append(r);card.append(l)});
        const actions=document.createElement('div');actions.className='decor-card-actions';const up=button('←',()=>{[slides[i-1],slides[i]]=[slides[i],slides[i-1]];selected=i-1;mark();render()});up.disabled=i===0;up.setAttribute('aria-label','Avancer le fond '+(i+1));const down=button('→',()=>{[slides[i+1],slides[i]]=[slides[i],slides[i+1]];selected=i+1;mark();render()});down.disabled=i===slides.length-1;down.setAttribute('aria-label','Reculer le fond '+(i+1));actions.append(up,down,button('Retirer',()=>{slides.splice(i,1);selected=Math.max(0,Math.min(selected,slides.length-1));mark();render()}),button('Aperçu',()=>{selected=i;preview()}));card.append(actions);cards.append(card)});document.getElementById('addBanner').disabled=slides.length>=3;preview();}
    async function readFile(file,index){if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>2*1024*1024){statusText('Choisis une image JPG ou PNG de moins de 2 Mo.',true);return;}try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const img=new Image();img.src=data;await img.decode();if(img.width>8000||img.height>8000||img.width*img.height>20000000)throw Error('Image trop grande.');if(index==null){if(slides.length>=3)return;slides.push({data,focal:65,mobileFocal:65});selected=slides.length-1}else{slides[index]={...slides[index],data};selected=index}mark();render()}catch(e){statusText('Impossible de lire cette image. '+(e.message||''),true)}}
    document.getElementById('addBanner').onclick=()=>{const f=document.createElement('input');f.type='file';f.accept='image/jpeg,image/png';f.onchange=()=>readFile(f.files[0],null);f.click()};
    document.getElementById('mobilePreview').onchange=preview;document.getElementById('decorInterval').oninput=mark;
    window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
    form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;form.inert=true;save.disabled=true;statusText('Enregistrement…');try{const result=await apiCall('/decor',{method:'PUT',body:JSON.stringify({version,intervalMs:Number(document.getElementById('decorInterval').value)*1000,slides:slides.map(s=>({id:s.id,data:s.data,focal:s.focal,mobileFocal:s.mobileFocal}))})});version=result.version;slides=result.slides;dirty=false;render();statusText('Décor enregistré. Tu peux actualiser l’accueil.')}catch(err){statusText(err.message,true)}finally{busy=false;form.inert=false;save.disabled=false}};
    try{const result=await apiCall('/decor');slides=result.slides;version=result.version;document.getElementById('decorInterval').value=result.intervalMs/1000;form.hidden=false;render();statusText(slides.length?'Décor chargé.':'Ajoute tes images pour remplacer le fond actuel.')}catch(err){statusText('Chargement impossible : '+err.message+' Vérifie que le nouveau backend est déployé.',true)}
})();
